// <auto-generated />
using BookNookApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookNookApi.Migrations
{
    [DbContext(typeof(BookNookDbContext))]
    [Migration("20240711194729_AddedRatingsAndFixedAuthorNames")]
    partial class AddedRatingsAndFixedAuthorNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookNookApi.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Harper Lee"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Sara Gruen"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Kathryn Stockett"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Alice "
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Liza Mundy"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Mary Ann Shaffer and Anne Barrows"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Andrea Van Landingham"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Anderson Cooper"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Laurence Leamer"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Anne Michaud"
                        },
                        new
                        {
                            Id = 11,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Tricia Levenseller"
                        },
                        new
                        {
                            Id = 12,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Lynn Painter"
                        },
                        new
                        {
                            Id = 13,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Ali Hazelwood"
                        },
                        new
                        {
                            Id = 14,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Linda Cheng"
                        },
                        new
                        {
                            Id = 15,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Rebeccas Renner"
                        },
                        new
                        {
                            Id = 16,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Caroline Hardaker"
                        },
                        new
                        {
                            Id = 17,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Lee Winter"
                        },
                        new
                        {
                            Id = 18,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Olivia Janae"
                        },
                        new
                        {
                            Id = 19,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Stephanie Shea"
                        },
                        new
                        {
                            Id = 20,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Kate Quinn"
                        },
                        new
                        {
                            Id = 21,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Kent Follett"
                        },
                        new
                        {
                            Id = 22,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Ken Follett"
                        },
                        new
                        {
                            Id = 23,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Jennifer Lyle"
                        },
                        new
                        {
                            Id = 24,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Tracy K. Smith"
                        },
                        new
                        {
                            Id = 25,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Sophie Cousens"
                        },
                        new
                        {
                            Id = 26,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Christina Henry"
                        },
                        new
                        {
                            Id = 27,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Darcy Coates"
                        },
                        new
                        {
                            Id = 28,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Mark Harmon"
                        },
                        new
                        {
                            Id = 29,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "Kelly And Zach Weinersmith"
                        },
                        new
                        {
                            Id = 30,
                            Biography = "Aliquam! Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus ex delectus! Ipsum quaerat exercitationem expedita placeat. Esse blanditiis, soluta perspiciatis tenetur unde corporis sequi eos cupiditate. Dolores, obcaecati explicabo",
                            Name = "John Wigger"
                        });
                });

            modelBuilder.Entity("BookNookApi.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/2657._SX300_.jpg",
                            Price = 150m,
                            Qty = 100,
                            Rating = "images/ratings/rating-20",
                            Title = "To Kill A Mockingbird"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/43641._SX300_.jpg",
                            Price = 125m,
                            Qty = 100,
                            Rating = "images/ratings/rating-30",
                            Title = "Water for Elephants"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/4667024.jpg",
                            Price = 100m,
                            Qty = 100,
                            Rating = "images/ratings/rating-10",
                            Title = "The Help"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/12232938._SX300_.jpg",
                            Price = 150m,
                            Qty = 100,
                            Rating = "images/ratings/rating-15",
                            Title = "Lovely Bones"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/34184307._SX300_.jpg",
                            Price = 150m,
                            Qty = 100,
                            Rating = "images/ratings/rating-35",
                            Title = "Code Girls"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/39832183.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-05",
                            Title = "The Guernsey"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/56359706._SX300_.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-30",
                            Title = "Hollywood Horrors"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/56382342.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-15",
                            Title = "Vanderbilt"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/57005206._SX300_.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-50",
                            Title = "Capote's Women"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/58524608._SX300_.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-45",
                            Title = "Why They Stay"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/59656615.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-45",
                            Title = "Vengeance Of The Pirate Queen"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/60197314.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-45",
                            Title = "Betting On You"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/60683957.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-45",
                            Title = "Check & Mate"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/63005207._SY475_.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-45",
                            Title = "Gorgeous Gruesome Faces"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/65211796.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-50",
                            Title = "Gator Country"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/80328993.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-45",
                            Title = "Mothtown"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/35335134.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-50",
                            Title = "The Brutal Truth"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/36649339.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-50",
                            Title = "Shades Of Blue"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/58443037.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-50",
                            Title = "Chef's Kiss"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/58490567.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-50",
                            Title = "The Diamond Eye"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/75434345.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-50",
                            Title = "The Fixer"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/81067992.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-35",
                            Title = "The Armor Of Light"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/86033921.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-45",
                            Title = "Swarm"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/112974900.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-25",
                            Title = "To Free The Captives"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/112976344.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-40",
                            Title = "The Good Part"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/122658643.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-45",
                            Title = "Good Girls Don't Die"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/123262468._SY475_.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-50",
                            Title = "Where He Can't Find You"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/123266603._SY475_.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-45",
                            Title = "Ghosts Of Honolulu"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/125084292.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-30",
                            Title = "A City On Mars"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/125423142.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-15",
                            Title = "The Hijacking Of American Flight 119"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            Description = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsa, itaque tempore autem, ullam vel veritatis laudantium enim officiis nemo quasi, dicta praesentium corrupti minus? Omnis fuga voluptatum deserunt ex ea? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed esse non vel, alias fuga pariatur aperiam dolorum numquam tempore possimus, aliquam soluta!",
                            ISBN = "978-3-16-148410-0",
                            ImageUrl = "images/128126768.jpg",
                            Price = 250m,
                            Qty = 120,
                            Rating = "images/ratings/rating-25",
                            Title = "A Woman I Know"
                        });
                });

            modelBuilder.Entity("BookNookApi.Entities.BookAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            BookId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            BookId = 2
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            BookId = 3
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            BookId = 4
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            BookId = 5
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            BookId = 6
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            BookId = 7
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            BookId = 8
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            BookId = 9
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 10,
                            BookId = 10
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 11,
                            BookId = 11
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 12,
                            BookId = 12
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 13,
                            BookId = 13
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 14,
                            BookId = 14
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 15,
                            BookId = 15
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            BookId = 16
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 17,
                            BookId = 17
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 18,
                            BookId = 18
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 19,
                            BookId = 19
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 20,
                            BookId = 20
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 17,
                            BookId = 21
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 22,
                            BookId = 22
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 23,
                            BookId = 23
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 24,
                            BookId = 24
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 25,
                            BookId = 25
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 26,
                            BookId = 26
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 27,
                            BookId = 27
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 28,
                            BookId = 28
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 29,
                            BookId = 29
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 30,
                            BookId = 30
                        });
                });

            modelBuilder.Entity("BookNookApi.Entities.BookCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Narrative"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Non-Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Romance"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Drama"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Horror"
                        });
                });

            modelBuilder.Entity("BookNookApi.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BookNookApi.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BookNookApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Phiwe"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Saba"
                        });
                });

            modelBuilder.Entity("BookNookApi.Entities.BookAuthor", b =>
                {
                    b.HasOne("BookNookApi.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookNookApi.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
